INSERT INTO `categories` (`id`, `name`) VALUES
(1, 'Állatok'),
(2, 'Család'),
(3, 'Egészség'),
(4, 'Elektronikus eszközök'),
(5, 'Emberek'),
(6, 'Étel, ital'),
(7, 'Ezotéria'),
(8, 'Párkapcsolat'),
(9, 'Fogyókúra'),
(10, 'Gyerekvállalás, nevelés'),
(11, 'Ismerkedés'),
(12, 'Közlekedés'),
(13, 'Közoktatás, tanulás'),
(14, 'Kultúra, közösség'),
(15, 'Otthon'),
(16, 'Politika'),
(17, 'Sport, mozgás'),
(18, 'Tech & kütyük'),
(19, 'Szépség és divat'),
(20, 'Szexualitás'),
(21, 'Szórakozás'),
(22, 'Tudomány'),
(23, 'Utazás'),
(24, 'Ünnep'),
(25, 'Üzlet és pénzügy'),
(26, 'Egyéb');